Example Dockerfile Explained
FROM node:14: # This line specifies the base image to use. In this case, it uses the official Node.js image with version 14.
WORKDIR /usr/src/app: # This sets the working directory inside the container to /usr/src/app.
*COPY package.json ./**: # This copies package.json and package-lock.json files to the working directory.
RUN npm install: # This installs the dependencies listed in package.json.
COPY . .: # This copies the rest of the application code to the working directory.
EXPOSE 3000: # This exposes port 3000, so the application is accessible from outside the container.
CMD ["node", "app.js"]: # This specifies the command to run the application, which in this case is node app.js.
